# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messaging_pb2 as messaging__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messaging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessagingServiceStub(object):
    """The messaging service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastMessage = channel.unary_unary(
                '/messaging.MessagingService/BroadcastMessage',
                request_serializer=messaging__pb2.BroadcastMessageRequest.SerializeToString,
                response_deserializer=messaging__pb2.BroadcastMessageResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.unary_stream(
                '/messaging.MessagingService/StreamMessages',
                request_serializer=messaging__pb2.StreamMessagesRequest.SerializeToString,
                response_deserializer=messaging__pb2.StreamMessagesResponse.FromString,
                _registered_method=True)


class MessagingServiceServicer(object):
    """The messaging service definition.
    """

    def BroadcastMessage(self, request, context):
        """Broadcasts a message to all clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Streams messages from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastMessage,
                    request_deserializer=messaging__pb2.BroadcastMessageRequest.FromString,
                    response_serializer=messaging__pb2.BroadcastMessageResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=messaging__pb2.StreamMessagesRequest.FromString,
                    response_serializer=messaging__pb2.StreamMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messaging.MessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messaging.MessagingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagingService(object):
    """The messaging service definition.
    """

    @staticmethod
    def BroadcastMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messaging.MessagingService/BroadcastMessage',
            messaging__pb2.BroadcastMessageRequest.SerializeToString,
            messaging__pb2.BroadcastMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/messaging.MessagingService/StreamMessages',
            messaging__pb2.StreamMessagesRequest.SerializeToString,
            messaging__pb2.StreamMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
